version: '3.3'
services:
    redpanda:
        command:
            - redpanda
            - start
            - --smp
            - '1'
            - --reserve-memory
            - 0M
            - --overprovisioned
            - --node-id
            - '0'
            - --kafka-addr
            - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
            - --advertise-kafka-addr
            - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
        image: vectorized/redpanda:v21.11.3
        container_name: redpanda
        ports:
            - 9092:9092
            - 29092:29092

    # zookeeper:
    #     image: docker.io/bitnami/zookeeper:3.7
    #     ports:
    #         - 2181:2181
    #     environment:
    #         - ALLOW_ANONYMOUS_LOGIN=yes

    # redpanda:
    #     image: docker.io/bitnami/kafka:3
    #     container_name: redpanda
    #     ports:
    #         - 9092:9092
    #     environment:
    #         - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #         - ALLOW_PLAINTEXT_LISTENER=yes
    #     depends_on:
    #         - zookeeper

    quarkus-app:
        build:
            context: .
            dockerfile: src/main/docker/Dockerfile.native
        container_name: quarkus-app-docker
        image: quarkus-app-img
        depends_on:
            - redpanda
